library(foreign) 
a = read.xport("./1 data preprocess/rawdata/LLCP2021.XPT")
class(a)
names(a)

table(a$CVDINFR4)
table(a$SEXVAR)
table(a$HEIGHT3)
table(a$WEIGHT2)
table(a$BLIND)
table(a$DEAF)
table(a$DIABETE4)
table(a$TOLDHI3)
table(a$BPHIGH6)
table(a$CHCKDNY2)
table(a$TOLDHEPC)
table(a$HAVEHEPB)
table(a$ALCDAY5)
table(a$SMOKE100)

b <- subset(a, select=c(CVDINFR4, SEXVAR, HEIGHT3, WEIGHT2, BLIND, DEAF, DIABETE4, TOLDHI3, BPHIGH6, CHCKDNY2, TOLDHEPC, HAVEHEPB, ALCDAY5, SMOKE100))
names(b) <- c("HEARTDISEASE", "SEX", "HEIGHT", "WEIGHT", "BLIND", "DEAF", "DIABETE", "CHOLESTEROL", "HYPERTENSION", "KIDNEY", "LIVER1", "LIVER2", "ALCOHOL", "SMOKE")
names(b)

write.csv(a, "./temp/brfss_raw.csv", row.names=F);print("a")
write.csv(b, "./temp/brfss.csv", row.names=F);print("b")
